[package]
name = "synapse-agent"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "synapse-agent"
path = "src/main.rs"

[dependencies]
synapse-common = { path = "../common" }
synapse-platform-macos = { path = "../platform-macos" }
arc-swap = "1"
crossbeam-channel = "0.5"
ctrlc = { version = "3", features = ["termination"] }
libc = "0.2"
log = "0.4"
maxminddb = "0.30"
ipnetwork = "0.21"
toml = "0.8"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rusqlite = { version = "0.31", features = ["bundled"] }
